### PR TITLE
Updated to use ros-sports/biped-interfaces

### PR DESCRIPTION
**Pull request by sidrdesai**
Hi Kenji,

I was testing out your ros2 packages, and it seemed like team_ijnek was pointing to ijnek/biped-interfaces, which seems to have been depricated in favor of ros-sports/biped-interfaces

### CODE REVIEW

**Comment by ijnek** [comment]
Thanks for this PR!

@sidrdesai I've added some more changes, please have a look. Also, note that the BASE_ANKLE_HEIGHT was -0.185, but this was changed to BASE_SOLE_HEIGHT with -0.230. This accounts for the additional [FootHeight](http://doc.aldebaran.com/1-14/_images/hardware_lengthfront_3.3.png) of (0.045m) of the NAO, that must be considered with the change from ankle -> sole.

**Comment by ijnek** [comment]
@sidrdesai ping

**Comment by sidrdesai** [comment]
Thanks, it looks like it's working now! We were able to make the robot kick
and crouch.

**Comment by ijnek** [comment]
That' great! I'll go ahead and merge this. Thanks for the contribution!

**Pull request merged**
